services:
  greedy:
    build:
      context: .
      dockerfile: ./greedy/Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./greedy/database:/app/database
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - greedy-network

networks:
  greedy-network:
    driver: bridge