services:
  greedy:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./next.config.mjs:/app/next.config.mjs
      - ./postcss.config.cjs:/app/postcss.config.cjs
      - ./tailwind.config.js:/app/tailwind.config.js
      - /app/node_modules
      - ./database:/app/database
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - DATA_DIR=/app/database
    profiles:
      - dev
    networks:
      - greedy-network

networks:
  greedy-network:
    driver: bridge

volumes:
  node_modules: